// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	category "gitlab.com/kazmerdome/best-ever-golang-starter/internal/module/category"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// CategoryDataloader is an autogenerated mock type for the CategoryDataloader type
type CategoryDataloader struct {
	mock.Mock
}

type CategoryDataloader_Expecter struct {
	mock *mock.Mock
}

func (_m *CategoryDataloader) EXPECT() *CategoryDataloader_Expecter {
	return &CategoryDataloader_Expecter{mock: &_m.Mock}
}

// ItemLoader provides a mock function with given fields: ctx, id
func (_m *CategoryDataloader) ItemLoader(ctx context.Context, id uuid.UUID) (*category.Category, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ItemLoader")
	}

	var r0 *category.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*category.Category, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *category.Category); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*category.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CategoryDataloader_ItemLoader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ItemLoader'
type CategoryDataloader_ItemLoader_Call struct {
	*mock.Call
}

// ItemLoader is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *CategoryDataloader_Expecter) ItemLoader(ctx interface{}, id interface{}) *CategoryDataloader_ItemLoader_Call {
	return &CategoryDataloader_ItemLoader_Call{Call: _e.mock.On("ItemLoader", ctx, id)}
}

func (_c *CategoryDataloader_ItemLoader_Call) Run(run func(ctx context.Context, id uuid.UUID)) *CategoryDataloader_ItemLoader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *CategoryDataloader_ItemLoader_Call) Return(_a0 *category.Category, _a1 error) *CategoryDataloader_ItemLoader_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CategoryDataloader_ItemLoader_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*category.Category, error)) *CategoryDataloader_ItemLoader_Call {
	_c.Call.Return(run)
	return _c
}

// NewCategoryDataloader creates a new instance of CategoryDataloader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryDataloader(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryDataloader {
	mock := &CategoryDataloader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
