// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postQuerier

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOne(ctx context.Context, arg CreateOneParams) (Post, error)
	DeleteOne(ctx context.Context, id uuid.UUID) error
	GetMany(ctx context.Context, arg GetManyParams) ([]Post, error)
	GetManyByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]Post, error)
	GetOneById(ctx context.Context, id uuid.UUID) (Post, error)
	UpdateOneById(ctx context.Context, arg UpdateOneByIdParams) (Post, error)
}

var _ Querier = (*Queries)(nil)
